
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Sep  1 2026 15:20:29 -03 (Sep  1 2026 18:20:29 UTC)

// Verification Directory fv/ecc_design 

module ecc_design(data_in_left, data_out_right_up, data_out_right_down,
     data_in_right_up, data_in_right_down, data_out_left, sel, flag,
     chip_sel_out, chip_sel);
  input [0:15] data_in_left, data_in_right_up, data_in_right_down;
  input [2:0] sel;
  input chip_sel;
  output [0:15] data_out_right_up, data_out_right_down, data_out_left;
  output [0:2] flag;
  output [1:0] chip_sel_out;
  wire [0:15] data_in_left, data_in_right_up, data_in_right_down;
  wire [2:0] sel;
  wire chip_sel;
  wire [0:15] data_out_right_up, data_out_right_down, data_out_left;
  wire [0:2] flag;
  wire [1:0] chip_sel_out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_41, n_42;
  wire n_43, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_54, n_55, n_56, n_57, n_58, n_59;
  wire n_60, n_61, n_62, n_63, n_64, n_65, n_66, n_67;
  wire n_68, n_69, n_70, n_71, n_72, n_73, n_74, n_75;
  wire n_76, n_77, n_78, n_79, n_80, n_81, n_82, n_83;
  wire n_84, n_85, n_86, n_87, n_88, n_89, n_90, n_91;
  wire n_92, n_93, n_94, n_95, n_96, n_97, n_99, n_100;
  wire n_101, n_102, n_103, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_117, n_119, n_124, n_126;
  wire n_127, n_129, n_134, n_137, n_151, n_152, n_153, n_154;
  wire n_155, n_156, n_157, n_158, n_159, n_160, n_161, n_162;
  wire n_163, n_164, n_165, n_166, n_167, n_168, n_169, n_170;
  wire n_171, n_172, n_173, n_175, n_176, n_177, n_178, n_179;
  wire n_180, n_183, n_186, n_187, n_188, n_189, n_190, n_191;
  wire n_192, n_193, n_194, n_195, n_196, n_197, n_198, n_199;
  wire n_200, n_201, n_202, n_203, n_204, n_205, n_206, n_207;
  wire n_208, n_209, n_210, n_211, n_212, n_213, n_214, n_215;
  wire n_216, n_217, n_218, n_219, n_220, n_221, n_222, n_223;
  wire n_224, n_225, n_226, n_227, n_228, n_229, n_230, n_231;
  wire n_232, n_233, n_234, n_235, n_236, n_237, n_238, n_239;
  wire n_240, n_241, n_242, n_243, n_244, n_245, n_246, n_247;
  wire n_248, n_249, n_250, n_251, n_252, n_253, n_254, n_255;
  wire n_256, n_257, n_258, n_259, n_260, n_261, n_262, n_263;
  wire n_264, n_265, n_266, n_267, n_268, n_269, n_270, n_271;
  wire n_272, n_273, n_274, n_275, n_276, n_277, n_278, n_279;
  wire n_280, n_281, n_283, n_284, n_285, n_286, n_287, n_288;
  wire n_289, n_290, n_291, n_292, n_293, n_294, n_295, n_296;
  wire n_297, n_298, n_299, n_300, n_301, n_302, n_303, n_304;
  wire n_305, n_306, n_307, n_308, n_309, n_310, n_311, n_313;
  wire n_314, n_315, n_317, n_318, n_321, n_322, n_325, n_326;
  wire n_327, n_328, n_329, n_330, n_331, n_332, n_334, n_335;
  wire n_336, n_337, n_338, n_339, n_340, n_341, n_342, n_352;
  wire n_353, n_354, n_355, n_390, n_391, n_416, n_417, n_418;
  wire n_419, n_436, n_437, n_448, n_470, n_481, n_491, n_492;
  wire n_496, n_497, n_498;
  sg13g2_inv_1 g19039(.A (n_355), .Y (data_out_left[4]));
  sg13g2_inv_1 g19040(.A (n_354), .Y (data_out_left[8]));
  sg13g2_a221oi_1 g19044__2398(.A1 (n_417), .A2 (data_in_right_up[4]),
       .B1 (n_315), .B2 (data_in_right_down[4]), .C1 (n_336), .Y
       (n_355));
  sg13g2_a221oi_1 g19045__5107(.A1 (n_416), .A2 (data_in_right_up[8]),
       .B1 (n_491), .B2 (data_in_right_down[8]), .C1 (n_334), .Y
       (n_354));
  sg13g2_o21ai_1 g19042__6260(.A1 (n_315), .A2 (n_327), .B1 (n_341), .Y
       (data_out_left[5]));
  sg13g2_nand2_1 g19036__4319(.A (n_338), .B (n_322), .Y
       (data_out_left[2]));
  sg13g2_nand2_1 g19038__8428(.A (n_330), .B (n_318), .Y
       (data_out_left[1]));
  sg13g2_nand2_1 g19035__5526(.A (n_328), .B (n_317), .Y
       (data_out_left[6]));
  sg13g2_nand2_1 g19048__6783(.A (n_329), .B (n_325), .Y
       (data_out_left[12]));
  sg13g2_o21ai_1 g19041__3680(.A1 (n_390), .A2 (n_326), .B1 (n_335), .Y
       (data_out_left[10]));
  sg13g2_nand2_1 g19037__1617(.A (n_332), .B (n_102), .Y
       (data_out_left[9]));
  sg13g2_nand2_1 g19043__2802(.A (n_340), .B (n_99), .Y
       (data_out_left[13]));
  sg13g2_nand2_1 g19034__1705(.A (n_342), .B (n_103), .Y
       (data_out_left[14]));
  sg13g2_a22oi_1 g19054__5122(.A1 (n_337), .A2 (n_186), .B1
       (data_in_right_up[11]), .B2 (n_321), .Y (n_342));
  sg13g2_a22oi_1 g19049__8246(.A1 (n_339), .A2 (n_153), .B1
       (data_in_right_down[5]), .B2 (n_315), .Y (n_341));
  sg13g2_a22oi_1 g19053__7098(.A1 (n_339), .A2 (n_159), .B1
       (data_in_right_up[7]), .B2 (n_331), .Y (n_340));
  sg13g2_a22oi_1 g19046__6131(.A1 (n_337), .A2 (n_163), .B1
       (data_in_right_up[2]), .B2 (n_417), .Y (n_338));
  sg13g2_a21oi_1 g19055__1881(.A1 (n_302), .A2 (n_314), .B1 (n_448), .Y
       (n_336));
  sg13g2_a22oi_1 g19050__5115(.A1 (n_337), .A2 (n_157), .B1
       (data_in_right_down[10]), .B2 (n_491), .Y (n_335));
  sg13g2_a21oi_1 g19058__7482(.A1 (n_297), .A2 (n_306), .B1 (n_134), .Y
       (n_334));
  sg13g2_a22oi_1 g19051__4733(.A1 (n_339), .A2 (n_156), .B1
       (data_in_right_up[6]), .B2 (n_331), .Y (n_332));
  sg13g2_a22oi_1 g19047__6161(.A1 (n_339), .A2 (n_165), .B1
       (data_in_right_up[1]), .B2 (n_418), .Y (n_330));
  sg13g2_a22oi_1 g19061__9315(.A1 (n_313), .A2 (n_43), .B1
       (data_in_right_down[12]), .B2 (n_391), .Y (n_329));
  sg13g2_a22oi_1 g19052__9945(.A1 (n_337), .A2 (n_176), .B1
       (data_in_right_up[6]), .B2 (n_417), .Y (n_328));
  sg13g2_nand2b_1 g19057__2883(.A_N (n_339), .B (data_in_right_up[5]),
       .Y (n_327));
  sg13g2_nand2b_1 g19056__2346(.A_N (n_337), .B (data_in_right_up[10]),
       .Y (n_326));
  sg13g2_a22oi_1 g19064__1666(.A1 (n_291), .A2 (n_311), .B1
       (data_in_right_up[12]), .B2 (n_416), .Y (n_325));
  sg13g2_o21ai_1 g19063__7410(.A1 (n_391), .A2 (n_298), .B1 (n_307), .Y
       (data_out_left[0]));
  sg13g2_nand2_1 g19069__6417(.A (n_293), .B (n_308), .Y
       (data_out_left[3]));
  sg13g2_a22oi_1 g19059__5477(.A1 (n_321), .A2 (data_in_right_up[8]),
       .B1 (data_in_right_down[2]), .B2 (n_315), .Y (n_322));
  sg13g2_nand2_1 g19067__2398(.A (n_289), .B (n_305), .Y
       (data_out_left[11]));
  sg13g2_nand2_1 g19068__5107(.A (n_294), .B (n_303), .Y
       (data_out_left[7]));
  sg13g2_a22oi_1 g19060__6260(.A1 (n_331), .A2 (data_in_right_up[4]),
       .B1 (data_in_right_down[1]), .B2 (n_491), .Y (n_318));
  sg13g2_a22oi_1 g19062__4319(.A1 (n_321), .A2 (data_in_right_up[9]),
       .B1 (data_in_right_down[6]), .B2 (n_391), .Y (n_317));
  sg13g2_o21ai_1 g19070__8428(.A1 (n_315), .A2 (n_287), .B1 (n_288), .Y
       (data_out_left[15]));
  sg13g2_a21o_1 g19073__5526(.A1 (n_497), .A2 (n_300), .B1 (n_299), .X
       (n_314));
  sg13g2_a21oi_1 g19074__6783(.A1 (n_497), .A2 (n_311), .B1 (n_290), .Y
       (n_313));
  sg13g2_a21oi_1 g19065__3680(.A1 (n_310), .A2 (n_286), .B1 (n_309), .Y
       (n_339));
  sg13g2_a21oi_1 g19066__1617(.A1 (n_310), .A2 (n_284), .B1 (n_309), .Y
       (n_337));
  sg13g2_a22oi_1 g19082__2802(.A1 (n_304), .A2 (data_in_right_up[12]),
       .B1 (data_in_right_down[3]), .B2 (n_390), .Y (n_308));
  sg13g2_a22oi_1 g19078__1705(.A1 (n_301), .A2 (n_162), .B1
       (data_in_right_down[0]), .B2 (n_492), .Y (n_307));
  sg13g2_a21o_1 g19075__5122(.A1 (n_497), .A2 (n_296), .B1 (n_295), .X
       (n_306));
  sg13g2_a22oi_1 g19084__8246(.A1 (n_304), .A2 (data_in_right_up[14]),
       .B1 (data_in_right_down[11]), .B2 (n_481), .Y (n_305));
  sg13g2_a22oi_1 g19086__7098(.A1 (n_304), .A2 (data_in_right_up[13]),
       .B1 (data_in_right_down[7]), .B2 (n_492), .Y (n_303));
  sg13g2_nand3_1 g19076__6131(.A (n_301), .B (n_300), .C (n_299), .Y
       (n_302));
  sg13g2_nand2b_1 g19079__1881(.A_N (n_301), .B (data_in_right_up[0]),
       .Y (n_298));
  sg13g2_nand3_1 g19077__5115(.A (n_301), .B (n_296), .C (n_295), .Y
       (n_297));
  sg13g2_nor2b_1 g19071__7482(.A (n_497), .B_N (n_310), .Y (n_331));
  sg13g2_nor2b_1 g19072__4733(.A (n_285), .B_N (n_310), .Y (n_321));
  sg13g2_a22oi_1 g19085__6161(.A1 (n_292), .A2 (n_151), .B1
       (data_in_right_up[7]), .B2 (n_419), .Y (n_294));
  sg13g2_a22oi_1 g19081__9315(.A1 (n_292), .A2 (n_160), .B1
       (data_in_right_up[3]), .B2 (n_418), .Y (n_293));
  sg13g2_and2_1 g19080__9945(.A (n_301), .B (n_290), .X (n_291));
  sg13g2_a22oi_1 g19087__2883(.A1 (n_292), .A2 (n_155), .B1
       (data_in_right_up[11]), .B2 (n_417), .Y (n_289));
  sg13g2_a22oi_1 g19088__2346(.A1 (n_292), .A2 (n_154), .B1
       (data_in_right_down[15]), .B2 (n_390), .Y (n_288));
  sg13g2_nand2b_1 g19089__1666(.A_N (n_292), .B (data_in_right_up[15]),
       .Y (n_287));
  sg13g2_nor2_1 g19092__6417(.A (n_309), .B (n_286), .Y (n_301));
  sg13g2_inv_1 g19096(.A (n_285), .Y (n_304));
  sg13g2_a21oi_1 g19083__5477(.A1 (n_264), .A2 (n_255), .B1 (n_283), .Y
       (n_310));
  sg13g2_nand2_1 g19098__2398(.A (n_284), .B (n_36), .Y (n_285));
  sg13g2_nor2_1 g19099__5107(.A (n_309), .B (n_284), .Y (n_292));
  sg13g2_nor3_1 g19091__6260(.A (sel[0]), .B (n_266), .C (n_281), .Y
       (n_283));
  sg13g2_a21oi_1 g19097__4319(.A1 (n_273), .A2 (n_270), .B1 (n_280), .Y
       (n_286));
  sg13g2_a21oi_1 g19101__8428(.A1 (n_271), .A2 (n_272), .B1 (n_268), .Y
       (n_284));
  sg13g2_dlhrq_1 decodificador1_bit2_reg(.RESET_B (1'b1), .GATE
       (n_279), .D (n_275), .Q (flag[1]));
  sg13g2_dllrq_1 decodificador1_bit3_reg(.RESET_B (1'b1), .GATE_N
       (n_281), .D (n_277), .Q (flag[2]));
  sg13g2_nor3_1 g19100__5526(.A (sel[0]), .B (n_278), .C (n_267), .Y
       (n_280));
  sg13g2_dlhrq_1 decodificador1_bit1_reg(.RESET_B (1'b1), .GATE
       (n_274), .D (n_276), .Q (flag[0]));
  sg13g2_nor3_1 g19103__6783(.A (n_278), .B (n_277), .C (n_276), .Y
       (n_279));
  sg13g2_or3_1 g19104__3680(.A (n_278), .B (n_275), .C (n_276), .X
       (n_281));
  sg13g2_nor3_1 g19102__1617(.A (n_278), .B (n_275), .C (n_277), .Y
       (n_274));
  sg13g2_a21oi_1 g19105__2802(.A1 (n_265), .A2 (n_272), .B1 (n_269), .Y
       (n_273));
  sg13g2_a21oi_1 g19110__1705(.A1 (n_262), .A2 (n_270), .B1 (n_269), .Y
       (n_271));
  sg13g2_nor3_1 g19106__5122(.A (sel[0]), .B (n_278), .C (n_261), .Y
       (n_268));
  sg13g2_inv_1 g19107(.A (n_276), .Y (n_267));
  sg13g2_o21ai_1 g19108__8246(.A1 (n_240), .A2 (n_258), .B1 (n_259), .Y
       (n_276));
  sg13g2_inv_1 g19109(.A (n_277), .Y (n_266));
  sg13g2_nor2_1 g19112__7098(.A (n_263), .B (n_256), .Y (n_265));
  sg13g2_nor4_1 g19114__6131(.A (n_269), .B (n_249), .C (n_260), .D
       (n_263), .Y (n_264));
  sg13g2_nand2b_1 g19118__1881(.A_N (n_263), .B (n_253), .Y (n_262));
  sg13g2_inv_1 g19113(.A (n_261), .Y (n_275));
  sg13g2_nor4_1 g19111__5115(.A (n_250), .B (n_251), .C (n_260), .D
       (n_248), .Y (n_277));
  sg13g2_o21ai_1 g19115__7482(.A1 (n_252), .A2 (n_257), .B1 (n_259), .Y
       (n_261));
  sg13g2_nand2b_1 g19116__4733(.A_N (n_257), .B (n_254), .Y (n_258));
  sg13g2_and3_1 g19119__6161(.A (n_255), .B (n_236), .C (n_254), .X
       (n_256));
  sg13g2_nand2b_1 g19122__9315(.A_N (n_252), .B (n_255), .Y (n_253));
  sg13g2_a21oi_1 g19117__9945(.A1 (n_251), .A2 (n_246), .B1 (n_250), .Y
       (n_259));
  sg13g2_o21ai_1 g19127__2883(.A1 (n_215), .A2 (n_212), .B1 (n_243), .Y
       (n_249));
  sg13g2_o21ai_1 g19121__2346(.A1 (n_210), .A2 (n_206), .B1 (n_247), .Y
       (n_248));
  sg13g2_nand2_1 g19120__1666(.A (n_247), .B (n_246), .Y (n_257));
  sg13g2_nor2_1 g19125__7410(.A (n_244), .B (n_245), .Y (n_263));
  sg13g2_nand2_1 g19126__6417(.A (n_239), .B (sel[0]), .Y (n_269));
  sg13g2_nand2_1 g19130__5477(.A (n_245), .B (n_244), .Y (n_255));
  sg13g2_nor3_1 g19129__2398(.A (n_235), .B (n_234), .C (n_233), .Y
       (n_250));
  sg13g2_nand2b_1 g19132__5107(.A_N (n_272), .B (n_270), .Y (n_243));
  sg13g2_a22oi_1 g19131__6260(.A1 (n_222), .A2 (n_237), .B1 (n_211),
       .B2 (n_238), .Y (n_278));
  sg13g2_nand2_1 g19123__4319(.A (n_241), .B (n_242), .Y (n_247));
  sg13g2_nor2_1 g19124__8428(.A (n_242), .B (n_241), .Y (n_251));
  sg13g2_xor2_1 g19128__5526(.A (n_254), .B (n_240), .X (n_260));
  sg13g2_a21o_1 g19133__6783(.A1 (n_238), .A2 (n_214), .B1 (n_237), .X
       (n_239));
  sg13g2_nor2_1 g19134__3680(.A (n_254), .B (n_236), .Y (n_252));
  sg13g2_a21oi_1 g19136__1617(.A1 (n_231), .A2 (n_229), .B1 (n_232), .Y
       (n_245));
  sg13g2_o21ai_1 g19137__2802(.A1 (n_235), .A2 (n_234), .B1 (n_233), .Y
       (n_246));
  sg13g2_o21ai_1 g19135__1705(.A1 (n_227), .A2 (n_228), .B1 (n_272), .Y
       (n_244));
  sg13g2_inv_1 g19139(.A (n_232), .Y (n_270));
  sg13g2_xor2_1 g19138__5122(.A (n_230), .B (n_226), .X (n_241));
  sg13g2_nor2b_1 g19140__8246(.A (n_231), .B_N (n_230), .Y (n_233));
  sg13g2_a21o_1 g19141__7098(.A1 (n_178), .A2 (n_179), .B1 (n_225), .X
       (n_237));
  sg13g2_nor2_1 g19142__6131(.A (n_229), .B (n_231), .Y (n_232));
  sg13g2_inv_1 g19144(.A (n_240), .Y (n_236));
  sg13g2_nand2_1 g19143__1881(.A (n_228), .B (n_227), .Y (n_272));
  sg13g2_a21oi_1 g19148__5115(.A1 (n_223), .A2 (n_224), .B1 (n_226), .Y
       (n_240));
  sg13g2_inv_1 g19149(.A (n_226), .Y (n_231));
  sg13g2_o21ai_1 g19151__7482(.A1 (n_175), .A2 (n_164), .B1 (n_221), .Y
       (n_225));
  sg13g2_xnor2_1 g19146__4733(.A (n_235), .B (n_234), .Y (n_242));
  sg13g2_xnor2_1 g19147__6161(.A (n_197), .B (n_218), .Y (n_254));
  sg13g2_nor2_1 g19152__9315(.A (n_217), .B (n_220), .Y (n_228));
  sg13g2_nor2_1 g19150__9945(.A (n_224), .B (n_223), .Y (n_226));
  sg13g2_nand3_1 g19145__2883(.A (n_219), .B (n_235), .C (n_208), .Y
       (n_222));
  sg13g2_a221oi_1 g19153__2346(.A1 (n_187), .A2 (n_100), .B1 (n_196),
       .B2 (n_172), .C1 (n_207), .Y (n_221));
  sg13g2_xnor2_1 g19156__1666(.A (n_199), .B (n_198), .Y (n_220));
  sg13g2_xor2_1 g19157__7410(.A (n_213), .B (n_203), .X (n_223));
  sg13g2_xnor2_1 g19154__6417(.A (n_209), .B (n_216), .Y (n_219));
  sg13g2_xor2_1 g19158__5477(.A (n_217), .B (n_216), .X (n_218));
  sg13g2_o21ai_1 g19155__2398(.A1 (n_191), .A2 (n_216), .B1 (n_215), .Y
       (n_234));
  sg13g2_or3_1 g19159__5107(.A (n_213), .B (n_189), .C (n_212), .X
       (n_214));
  sg13g2_nand3b_1 g19162__6260(.A_N (n_210), .B (n_209), .C (n_205), .Y
       (n_211));
  sg13g2_a21oi_1 g19161__4319(.A1 (n_208), .A2 (n_204), .B1 (n_209), .Y
       (n_230));
  sg13g2_and2_1 g19160__8428(.A (n_200), .B (n_212), .X (n_227));
  sg13g2_a21oi_1 g19163__5526(.A1 (n_201), .A2 (n_213), .B1 (n_202), .Y
       (n_229));
  sg13g2_a22oi_1 g19166__6783(.A1 (n_195), .A2 (n_173), .B1 (n_152),
       .B2 (n_188), .Y (n_207));
  sg13g2_nand2b_1 g19165__3680(.A_N (n_215), .B (n_205), .Y (n_206));
  sg13g2_nand3b_1 g19164__1617(.A_N (n_215), .B (n_204), .C (n_224), .Y
       (n_238));
  sg13g2_nand2b_1 g19167__2802(.A_N (n_202), .B (n_201), .Y (n_203));
  sg13g2_o21ai_1 g19168__1705(.A1 (n_194), .A2 (n_199), .B1 (n_190), .Y
       (n_200));
  sg13g2_xnor2_1 g19169__5122(.A (n_177), .B (n_197), .Y (n_198));
  sg13g2_nand2_1 g19173__8246(.A (n_192), .B (n_193), .Y (n_208));
  sg13g2_xnor2_1 g19170__7098(.A (n_205), .B (n_210), .Y (n_216));
  sg13g2_o21ai_1 g19177__6131(.A1 (n_137), .A2 (n_158), .B1 (n_195), .Y
       (n_196));
  sg13g2_nand2_1 g19174__1881(.A (n_199), .B (n_194), .Y (n_212));
  sg13g2_nor2_1 g19183__5115(.A (n_193), .B (n_192), .Y (n_209));
  sg13g2_nor2_1 g19171__7482(.A (n_217), .B (n_190), .Y (n_191));
  sg13g2_nand2b_1 g19172__4733(.A_N (n_189), .B (n_204), .Y (n_201));
  sg13g2_nor2b_1 g19182__6161(.A (n_204), .B_N (n_189), .Y (n_202));
  sg13g2_nand2b_1 g19176__9315(.A_N (n_205), .B (n_210), .Y (n_235));
  sg13g2_nand2_1 g19175__9945(.A (n_190), .B (n_217), .Y (n_215));
  sg13g2_a21oi_1 g19184__2883(.A1 (n_101), .A2 (n_296), .B1 (n_187), .Y
       (n_188));
  sg13g2_xor2_1 g19205__2346(.A (data_in_right_up[11]), .B (n_311), .X
       (n_186));
  sg13g2_o21ai_1 g19181__1666(.A1 (n_129), .A2 (n_183), .B1 (n_167), .Y
       (data_out_right_down[4]));
  sg13g2_o21ai_1 g19179__7410(.A1 (n_127), .A2 (n_183), .B1 (n_166), .Y
       (data_out_right_down[5]));
  sg13g2_o21ai_1 g19180__6417(.A1 (n_119), .A2 (n_180), .B1 (n_171), .Y
       (data_out_right_down[6]));
  sg13g2_o21ai_1 g19178__5477(.A1 (n_124), .A2 (n_180), .B1 (n_170), .Y
       (data_out_right_down[7]));
  sg13g2_nor2_1 g19196__2398(.A (n_179), .B (n_178), .Y (n_195));
  sg13g2_inv_1 g19201(.A (n_177), .Y (n_194));
  sg13g2_inv_1 g19202(.A (n_190), .Y (n_197));
  sg13g2_xnor2_1 g19207__5107(.A (data_in_right_up[9]), .B (n_175), .Y
       (n_176));
  sg13g2_nand2b_1 g19221__6260(.A_N (sel[2]), .B (n_496), .Y
       (chip_sel_out[1]));
  sg13g2_inv_1 g19223(.A (n_172), .Y (n_173));
  sg13g2_xor2_1 g19213__4319(.A (n_8), .B (n_498), .X (n_193));
  sg13g2_a22oi_1 g19186__8428(.A1 (n_169), .A2 (n_68), .B1 (n_73), .B2
       (n_168), .Y (n_171));
  sg13g2_a22oi_1 g19188__5526(.A1 (n_169), .A2 (n_59), .B1 (n_62), .B2
       (n_168), .Y (n_170));
  sg13g2_a22oi_1 g19189__6783(.A1 (n_169), .A2 (n_80), .B1 (n_66), .B2
       (n_168), .Y (n_167));
  sg13g2_a22oi_1 g19190__3680(.A1 (n_169), .A2 (n_71), .B1 (n_78), .B2
       (n_168), .Y (n_166));
  sg13g2_xnor2_1 g19193__1617(.A (data_in_right_up[4]), .B (n_164), .Y
       (n_165));
  sg13g2_xnor2_1 g19194__2802(.A (data_in_right_up[8]), .B (n_161), .Y
       (n_163));
  sg13g2_xnor2_1 g19195__1705(.A (data_in_right_up[0]), .B (n_161), .Y
       (n_162));
  sg13g2_xnor2_1 g19212__5122(.A (data_in_right_up[12]), .B (n_164), .Y
       (n_160));
  sg13g2_xnor2_1 g19211__8246(.A (data_in_right_up[7]), .B (n_158), .Y
       (n_159));
  sg13g2_xor2_1 g19210__7098(.A (data_in_right_up[10]), .B (n_296), .X
       (n_157));
  sg13g2_xor2_1 g19209__6131(.A (data_in_right_up[6]), .B (n_179), .X
       (n_156));
  sg13g2_xor2_1 g19203__1881(.A (data_in_right_up[14]), .B (n_179), .X
       (n_155));
  sg13g2_xnor2_1 g19204__5115(.A (data_in_right_up[15]), .B (n_158), .Y
       (n_154));
  sg13g2_xnor2_1 g19206__7482(.A (data_in_right_up[5]), .B (n_152), .Y
       (n_153));
  sg13g2_xnor2_1 g19208__4733(.A (data_in_right_up[13]), .B (n_152), .Y
       (n_151));
  sg13g2_xnor2_1 g19214__6161(.A (n_22), .B (n_96), .Y (n_177));
  sg13g2_xor2_1 g19197__9315(.A (n_76), .B (n_82), .X (n_192));
  sg13g2_xnor2_1 g19200__9945(.A (n_9), .B (n_75), .Y (n_213));
  sg13g2_xor2_1 g19198__2883(.A (n_24), .B (n_56), .X (n_224));
  sg13g2_xnor2_1 g19199__2346(.A (n_35), .B (n_77), .Y (n_189));
  sg13g2_inv_1 g19235(.A (n_107), .Y (data_out_right_up[2]));
  sg13g2_inv_1 g19234(.A (n_108), .Y (data_out_right_up[14]));
  sg13g2_o21ai_1 g19191__1666(.A1 (n_448), .A2 (n_79), .B1 (n_88), .Y
       (data_out_right_down[0]));
  sg13g2_o21ai_1 g19185__7410(.A1 (n_134), .A2 (n_69), .B1 (n_85), .Y
       (data_out_right_down[1]));
  sg13g2_o21ai_1 g19187__6417(.A1 (n_448), .A2 (n_60), .B1 (n_84), .Y
       (data_out_right_down[2]));
  sg13g2_o21ai_1 g19192__5477(.A1 (n_134), .A2 (n_63), .B1 (n_91), .Y
       (data_out_right_down[3]));
  sg13g2_inv_1 g19233(.A (n_117), .Y (data_out_right_up[6]));
  sg13g2_inv_1 g19232(.A (n_110), .Y (data_out_right_up[12]));
  sg13g2_inv_1 g19231(.A (n_111), .Y (data_out_right_up[7]));
  sg13g2_inv_1 g19230(.A (n_112), .Y (data_out_right_up[11]));
  sg13g2_inv_1 g19229(.A (n_113), .Y (data_out_right_up[4]));
  sg13g2_inv_1 g19227(.A (n_109), .Y (data_out_right_up[8]));
  sg13g2_inv_1 g19228(.A (n_115), .Y (data_out_right_up[3]));
  sg13g2_nand2_1 g19226__2398(.A (n_137), .B (n_158), .Y (n_172));
  sg13g2_nand2_1 g19225__5107(.A (n_164), .B (n_175), .Y (n_187));
  sg13g2_xnor2_1 g19215__6260(.A (n_30), .B (n_54), .Y (n_199));
  sg13g2_xnor2_1 g19220__4319(.A (n_51), .B (n_86), .Y (n_190));
  sg13g2_xnor2_1 g19216__8428(.A (n_81), .B (n_48), .Y (n_204));
  sg13g2_xnor2_1 g19218__5526(.A (n_15), .B (n_50), .Y (n_205));
  sg13g2_xnor2_1 g19219__6783(.A (n_53), .B (n_52), .Y (n_210));
  sg13g2_xnor2_1 g19217__3680(.A (n_33), .B (n_55), .Y (n_217));
  sg13g2_o21ai_1 g19244__1617(.A1 (n_6), .A2 (n_437), .B1 (n_97), .Y
       (data_out_right_down[8]));
  sg13g2_o21ai_1 g19247__2802(.A1 (n_14), .A2 (n_436), .B1 (n_89), .Y
       (data_out_right_down[10]));
  sg13g2_nand2b_1 g19222__1705(.A_N (sel[2]), .B (n_74), .Y
       (chip_sel_out[0]));
  sg13g2_o21ai_1 g19245__5122(.A1 (n_12), .A2 (n_436), .B1 (n_87), .Y
       (data_out_right_down[9]));
  sg13g2_nor2b_1 g19305__8246(.A (n_126), .B_N (data_in_left[0]), .Y
       (data_out_right_up[0]));
  sg13g2_o21ai_1 g19238__7098(.A1 (n_129), .A2 (n_437), .B1 (n_46), .Y
       (data_out_right_up[1]));
  sg13g2_nor2_1 g19312__6131(.A (n_127), .B (n_126), .Y
       (data_out_right_up[5]));
  sg13g2_o21ai_1 g19256__1881(.A1 (n_124), .A2 (n_436), .B1 (n_47), .Y
       (data_out_right_up[13]));
  sg13g2_o21ai_1 g19236__5115(.A1 (n_2), .A2 (n_436), .B1 (n_90), .Y
       (data_out_right_down[11]));
  sg13g2_o21ai_1 g19250__7482(.A1 (n_20), .A2 (n_436), .B1 (n_92), .Y
       (data_out_right_down[12]));
  sg13g2_o21ai_1 g19254__4733(.A1 (n_5), .A2 (n_437), .B1 (n_95), .Y
       (data_out_right_down[15]));
  sg13g2_o21ai_1 g19243__6161(.A1 (n_119), .A2 (n_436), .B1 (n_45), .Y
       (data_out_right_up[9]));
  sg13g2_nor2b_1 g19315__9315(.A (n_126), .B_N (data_in_left[15]), .Y
       (data_out_right_up[15]));
  sg13g2_nand2b_1 g19224__9945(.A_N (n_296), .B (n_161), .Y (n_178));
  sg13g2_a22oi_1 g19255__2883(.A1 (n_416), .A2 (data_in_left[6]), .B1
       (data_in_left[9]), .B2 (n_470), .Y (n_117));
  sg13g2_nor2b_1 g19302__2346(.A (n_126), .B_N (data_in_left[10]), .Y
       (data_out_right_up[10]));
  sg13g2_a22oi_1 g19241__1666(.A1 (n_419), .A2 (data_in_left[3]), .B1
       (data_in_left[12]), .B2 (n_114), .Y (n_115));
  sg13g2_a22oi_1 g19246__7410(.A1 (n_418), .A2 (data_in_left[4]), .B1
       (data_in_left[1]), .B2 (n_114), .Y (n_113));
  sg13g2_a22oi_1 g19248__6417(.A1 (n_419), .A2 (data_in_left[11]), .B1
       (data_in_left[14]), .B2 (n_470), .Y (n_112));
  sg13g2_a22oi_1 g19249__5477(.A1 (n_416), .A2 (data_in_left[7]), .B1
       (data_in_left[13]), .B2 (n_114), .Y (n_111));
  sg13g2_a22oi_1 g19251__2398(.A1 (n_419), .A2 (data_in_left[12]), .B1
       (data_in_left[3]), .B2 (n_470), .Y (n_110));
  sg13g2_a22oi_1 g19239__5107(.A1 (n_418), .A2 (data_in_left[8]), .B1
       (data_in_left[2]), .B2 (n_114), .Y (n_109));
  sg13g2_a22oi_1 g19257__6260(.A1 (n_417), .A2 (data_in_left[14]), .B1
       (data_in_left[11]), .B2 (n_470), .Y (n_108));
  sg13g2_a22oi_1 g19261__4319(.A1 (n_416), .A2 (data_in_left[2]), .B1
       (data_in_left[8]), .B2 (n_114), .Y (n_107));
  sg13g2_o21ai_1 g19253__8428(.A1 (n_11), .A2 (n_437), .B1 (n_94), .Y
       (data_out_right_down[14]));
  sg13g2_o21ai_1 g19252__5526(.A1 (n_21), .A2 (n_437), .B1 (n_93), .Y
       (data_out_right_down[13]));
  sg13g2_inv_1 g19264(.A (n_175), .Y (n_300));
  sg13g2_inv_1 g19267(.A (n_137), .Y (n_311));
  sg13g2_a22oi_1 g19237__3680(.A1 (n_390), .A2
       (data_in_right_down[14]), .B1 (data_in_right_up[14]), .B2
       (n_419), .Y (n_103));
  sg13g2_a22oi_1 g19240__1617(.A1 (n_481), .A2 (data_in_right_down[9]),
       .B1 (data_in_right_up[9]), .B2 (n_418), .Y (n_102));
  sg13g2_xnor2_1 g19296__2802(.A (data_in_right_down[14]), .B (n_41),
       .Y (n_137));
  sg13g2_xnor2_1 g19292__1705(.A (data_in_right_down[10]), .B (n_42),
       .Y (n_175));
  sg13g2_inv_1 g19266(.A (n_161), .Y (n_101));
  sg13g2_inv_1 g19265(.A (n_152), .Y (n_100));
  sg13g2_a22oi_1 g19242__5122(.A1 (n_391), .A2
       (data_in_right_down[13]), .B1 (data_in_right_up[13]), .B2
       (n_417), .Y (n_99));
  sg13g2_nand2_1 g19300__7098(.A (n_391), .B (data_in_left[8]), .Y
       (n_97));
  sg13g2_xnor2_1 g19288__6131(.A (data_in_right_down[4]), .B (n_7), .Y
       (n_96));
  sg13g2_nand2_1 g19313__1881(.A (n_390), .B (data_in_left[15]), .Y
       (n_95));
  sg13g2_nand2_1 g19311__5115(.A (n_492), .B (data_in_left[14]), .Y
       (n_94));
  sg13g2_nand2_1 g19310__7482(.A (n_315), .B (data_in_left[13]), .Y
       (n_93));
  sg13g2_nand2_1 g19309__4733(.A (n_391), .B (data_in_left[12]), .Y
       (n_92));
  sg13g2_nand2_1 g19308__6161(.A (n_390), .B (data_in_left[3]), .Y
       (n_91));
  sg13g2_nand2_1 g19306__9315(.A (n_481), .B (data_in_left[11]), .Y
       (n_90));
  sg13g2_nand2_1 g19297__9945(.A (n_492), .B (data_in_left[10]), .Y
       (n_89));
  sg13g2_nand2_1 g19298__2883(.A (n_391), .B (data_in_left[0]), .Y
       (n_88));
  sg13g2_nand2_1 g19299__2346(.A (n_390), .B (data_in_left[9]), .Y
       (n_87));
  sg13g2_xor2_1 g19287__1666(.A (data_in_right_down[2]), .B (n_49), .X
       (n_86));
  sg13g2_nand2_1 g19301__7410(.A (n_481), .B (data_in_left[1]), .Y
       (n_85));
  sg13g2_nand2_1 g19303__6417(.A (n_491), .B (data_in_left[2]), .Y
       (n_84));
  sg13g2_xnor2_1 g19294__5477(.A (data_in_right_down[11]), .B (n_26),
       .Y (n_152));
  sg13g2_xnor2_1 g19293__2398(.A (data_in_right_down[9]), .B (n_16), .Y
       (n_164));
  sg13g2_xnor2_1 g19289__5107(.A (data_in_right_down[15]), .B (n_23),
       .Y (n_158));
  sg13g2_xnor2_1 g19295__6260(.A (data_in_right_down[8]), .B (n_18), .Y
       (n_161));
  sg13g2_inv_1 g19317(.A (n_83), .Y (n_126));
  sg13g2_xor2_1 g19290__4319(.A (data_in_right_down[13]), .B (n_3), .X
       (n_179));
  sg13g2_xor2_1 g19291__8428(.A (data_in_right_down[12]), .B (n_19), .X
       (n_296));
  sg13g2_xnor2_1 g19286__5526(.A (data_in_right_up[10]), .B (n_81), .Y
       (n_82));
  sg13g2_xor2_1 g19258__6783(.A (n_65), .B (n_72), .X (n_80));
  sg13g2_xnor2_1 g19259__3680(.A (n_10), .B (n_13), .Y (n_79));
  sg13g2_xor2_1 g19260__1617(.A (n_57), .B (n_70), .X (n_78));
  sg13g2_xnor2_1 g19262__2802(.A (data_in_right_up[13]), .B (n_76), .Y
       (n_77));
  sg13g2_xnor2_1 g19263__1705(.A (data_in_right_down[7]), .B (n_25), .Y
       (n_75));
  sg13g2_xnor2_1 g19268__5122(.A (chip_sel), .B (n_416), .Y (n_74));
  sg13g2_xor2_1 g19269__8246(.A (n_72), .B (n_67), .X (n_73));
  sg13g2_xor2_1 g19270__7098(.A (n_61), .B (n_70), .X (n_71));
  sg13g2_xnor2_1 g19272__6131(.A (n_29), .B (n_31), .Y (n_69));
  sg13g2_xor2_1 g19273__1881(.A (n_64), .B (n_67), .X (n_68));
  sg13g2_xor2_1 g19274__5115(.A (n_65), .B (n_64), .X (n_66));
  sg13g2_xnor2_1 g19275__7482(.A (n_17), .B (n_27), .Y (n_63));
  sg13g2_xor2_1 g19276__4733(.A (n_58), .B (n_61), .X (n_62));
  sg13g2_xnor2_1 g19277__6161(.A (n_32), .B (n_34), .Y (n_60));
  sg13g2_xor2_1 g19278__9315(.A (n_58), .B (n_57), .X (n_59));
  sg13g2_xnor2_1 g19279__9945(.A (data_in_right_down[3]), .B (n_28), .Y
       (n_56));
  sg13g2_xnor2_1 g19280__2883(.A (data_in_right_down[0]), .B (n_4), .Y
       (n_55));
  sg13g2_xor2_1 g19281__2346(.A (data_in_right_up[6]), .B (n_53), .X
       (n_54));
  sg13g2_xnor2_1 g19282__1666(.A (data_in_right_up[2]), .B (n_51), .Y
       (n_52));
  sg13g2_xor2_1 g19283__7410(.A (data_in_right_up[0]), .B (n_49), .X
       (n_50));
  sg13g2_xor2_1 g19284__6417(.A (data_in_right_down[1]), .B (n_37), .X
       (n_48));
  sg13g2_and2_1 g19332__5477(.A (n_36), .B (sel[0]), .X (n_168));
  sg13g2_nand2_1 g19314__2398(.A (n_418), .B (data_in_left[13]), .Y
       (n_47));
  sg13g2_nand2_1 g19307__5107(.A (n_417), .B (data_in_left[1]), .Y
       (n_46));
  sg13g2_nand2_1 g19304__6260(.A (n_419), .B (data_in_left[9]), .Y
       (n_45));
  sg13g2_inv_1 g19322(.A (n_391), .Y (n_183));
  sg13g2_inv_1 g19320(.A (n_390), .Y (n_180));
  sg13g2_inv_1 g19378(.A (n_448), .Y (n_43));
  sg13g2_inv_1 g19319(.A (n_315), .Y (n_83));
  sg13g2_nor2_1 g19345__4319(.A (sel[0]), .B (n_309), .Y (n_169));
  sg13g2_inv_1 g19379(.A (n_134), .Y (n_114));
  sg13g2_xnor2_1 g19365__8428(.A (data_in_right_up[9]), .B (n_299), .Y
       (n_42));
  sg13g2_xnor2_1 g19369__5526(.A (data_in_right_up[11]), .B (n_290), .Y
       (n_41));
  sg13g2_nor3_1 g19349__6783(.A (sel[1]), .B (sel[2]), .C (n_0), .Y
       (n_352));
  sg13g2_inv_1 g19382(.A (n_309), .Y (n_36));
  sg13g2_xor2_1 g19361__3680(.A (data_in_right_up[14]), .B
       (data_in_right_up[12]), .X (n_35));
  sg13g2_xor2_1 g19330__1617(.A (data_in_left[4]), .B
       (data_in_left[1]), .X (n_34));
  sg13g2_xor2_1 g19372__2802(.A (data_in_right_up[7]), .B
       (data_in_right_up[2]), .X (n_33));
  sg13g2_xor2_1 g19368__1705(.A (data_in_left[12]), .B
       (data_in_left[9]), .X (n_32));
  sg13g2_xor2_1 g19325__5122(.A (data_in_left[6]), .B
       (data_in_left[3]), .X (n_31));
  sg13g2_xnor2_1 g19326__8246(.A (data_in_right_up[5]), .B
       (data_in_right_up[4]), .Y (n_30));
  sg13g2_xor2_1 g19375__7098(.A (data_in_left[14]), .B
       (data_in_left[11]), .X (n_29));
  sg13g2_xor2_1 g19327__6131(.A (data_in_right_up[13]), .B
       (data_in_right_up[8]), .X (n_28));
  sg13g2_xor2_1 g19328__1881(.A (data_in_left[7]), .B
       (data_in_left[2]), .X (n_27));
  sg13g2_xor2_1 g19323__5115(.A (data_in_right_up[13]), .B
       (data_in_right_up[5]), .X (n_26));
  sg13g2_xor2_1 g19331__7482(.A (data_in_right_up[9]), .B
       (data_in_right_up[8]), .X (n_25));
  sg13g2_xor2_1 g19371__4733(.A (data_in_right_up[15]), .B
       (data_in_right_up[10]), .X (n_24));
  sg13g2_xor2_1 g19370__6161(.A (data_in_right_up[15]), .B
       (data_in_right_up[7]), .X (n_23));
  sg13g2_xnor2_1 g19363__9315(.A (data_in_right_up[2]), .B
       (data_in_right_up[3]), .Y (n_22));
  sg13g2_xnor2_1 g19355__9945(.A (data_in_left[11]), .B
       (data_in_left[9]), .Y (n_21));
  sg13g2_xnor2_1 g19357__2883(.A (data_in_left[10]), .B
       (data_in_left[8]), .Y (n_20));
  sg13g2_xor2_1 g19358__2346(.A (data_in_right_up[10]), .B
       (data_in_right_up[2]), .X (n_19));
  sg13g2_xor2_1 g19342__1666(.A (data_in_left[4]), .B
       (data_in_left[0]), .X (n_65));
  sg13g2_xor2_1 g19343__7410(.A (data_in_left[15]), .B
       (data_in_left[11]), .X (n_70));
  sg13g2_xnor2_1 g19344__6417(.A (data_in_right_up[6]), .B
       (data_in_right_up[3]), .Y (n_51));
  sg13g2_xor2_1 g19334__5477(.A (data_in_left[14]), .B
       (data_in_left[10]), .X (n_61));
  sg13g2_xor2_1 g19337__2398(.A (data_in_left[7]), .B
       (data_in_left[3]), .X (n_57));
  sg13g2_xor2_1 g19338__5107(.A (data_in_left[5]), .B
       (data_in_left[1]), .X (n_72));
  sg13g2_xnor2_1 g19340__6260(.A (data_in_right_up[7]), .B
       (data_in_right_down[6]), .Y (n_53));
  sg13g2_o21ai_1 g19348__4319(.A1 (sel[0]), .A2 (sel[1]), .B1 (n_1), .Y
       (n_353));
  sg13g2_xor2_1 g19362__8428(.A (data_in_right_up[8]), .B
       (data_in_right_up[0]), .X (n_18));
  sg13g2_xor2_1 g19367__5526(.A (data_in_left[15]), .B
       (data_in_left[10]), .X (n_17));
  sg13g2_xor2_1 g19366__6783(.A (data_in_right_up[12]), .B
       (data_in_right_up[4]), .X (n_16));
  sg13g2_xnor2_1 g19373__3680(.A (data_in_right_up[5]), .B
       (data_in_right_down[4]), .Y (n_15));
  sg13g2_xnor2_1 g19353__1617(.A (data_in_left[6]), .B
       (data_in_left[4]), .Y (n_14));
  sg13g2_xor2_1 g19324__2802(.A (data_in_left[0]), .B
       (data_in_left[5]), .X (n_13));
  sg13g2_xnor2_1 g19352__1705(.A (data_in_left[3]), .B
       (data_in_left[1]), .Y (n_12));
  sg13g2_xnor2_1 g19356__5122(.A (data_in_left[14]), .B
       (data_in_left[12]), .Y (n_11));
  sg13g2_xor2_1 g19360__8246(.A (data_in_left[13]), .B
       (data_in_left[8]), .X (n_10));
  sg13g2_xor2_1 g19364__7098(.A (data_in_right_up[11]), .B
       (data_in_right_up[10]), .X (n_9));
  sg13g2_xnor2_1 g19376__6131(.A (data_in_right_up[13]), .B
       (data_in_right_down[7]), .Y (n_8));
  sg13g2_xnor2_1 g19374__1881(.A (data_in_right_up[0]), .B
       (data_in_right_up[1]), .Y (n_7));
  sg13g2_xnor2_1 g19354__5115(.A (data_in_left[2]), .B
       (data_in_left[0]), .Y (n_6));
  sg13g2_xnor2_1 g19351__7482(.A (data_in_left[15]), .B
       (data_in_left[13]), .Y (n_5));
  sg13g2_xnor2_1 g19359__4733(.A (data_in_right_up[0]), .B
       (data_in_right_up[5]), .Y (n_4));
  sg13g2_xor2_1 g19329__6161(.A (data_in_right_up[14]), .B
       (data_in_right_up[6]), .X (n_3));
  sg13g2_xnor2_1 g19350__9315(.A (data_in_left[7]), .B
       (data_in_left[5]), .Y (n_2));
  sg13g2_xnor2_1 g19347__9945(.A (data_in_right_up[4]), .B
       (data_in_right_up[1]), .Y (n_49));
  sg13g2_xnor2_1 g19333__2883(.A (data_in_right_up[12]), .B
       (data_in_right_up[9]), .Y (n_37));
  sg13g2_xnor2_1 g19335__2346(.A (data_in_right_up[14]), .B
       (data_in_right_up[11]), .Y (n_81));
  sg13g2_xor2_1 g19339__1666(.A (data_in_right_down[5]), .B
       (data_in_right_up[15]), .X (n_76));
  sg13g2_xor2_1 g19336__7410(.A (data_in_left[12]), .B
       (data_in_left[8]), .X (n_64));
  sg13g2_xor2_1 g19341__6417(.A (data_in_left[6]), .B
       (data_in_left[2]), .X (n_58));
  sg13g2_xor2_1 g19346__5477(.A (data_in_left[13]), .B
       (data_in_left[9]), .X (n_67));
  sg13g2_nand2_1 g19384__2398(.A (n_1), .B (sel[1]), .Y (n_309));
  sg13g2_inv_1 g19390(.A (sel[0]), .Y (n_0));
  sg13g2_inv_1 g19393(.A (data_in_left[7]), .Y (n_124));
  sg13g2_inv_1 g19385(.A (sel[2]), .Y (n_1));
  sg13g2_inv_1 g19386(.A (data_in_left[5]), .Y (n_127));
  sg13g2_inv_1 g19389(.A (data_in_right_up[2]), .Y (n_295));
  sg13g2_inv_1 g19392(.A (data_in_left[4]), .Y (n_129));
  sg13g2_inv_1 g19391(.A (data_in_left[6]), .Y (n_119));
  sg13g2_inv_1 g19387(.A (data_in_right_up[1]), .Y (n_299));
  sg13g2_inv_1 g19388(.A (data_in_right_up[3]), .Y (n_290));
  sg13g2_buf_1 drc_buf_sp19408(.A (n_352), .X (n_390));
  sg13g2_buf_1 drc_buf_sp19409(.A (n_352), .X (n_391));
  sg13g2_buf_1 drc_buf_sp19433(.A (n_353), .X (n_416));
  sg13g2_buf_1 drc_buf_sp19434(.A (n_353), .X (n_417));
  sg13g2_buf_1 drc_buf_sp19435(.A (n_353), .X (n_418));
  sg13g2_buf_1 drc_buf_sp19436(.A (n_353), .X (n_419));
  sg13g2_buf_1 drc_buf_sp19453(.A (n_436), .X (n_437));
  sg13g2_buf_1 drc_buf_sp19454(.A (n_134), .X (n_436));
  sg13g2_buf_1 drc_buf_sp19463(.A (n_134), .X (n_448));
  sg13g2_buf_1 drc_buf_sp19464(.A (n_309), .X (n_134));
  sg13g2_buf_1 drc_buf_sp19483(.A (n_114), .X (n_470));
  sg13g2_buf_1 drc_buf_sp19493(.A (n_315), .X (n_481));
  sg13g2_buf_1 drc_buf_sp19494(.A (n_352), .X (n_315));
  sg13g2_buf_1 drc_buf_sp19503(.A (n_491), .X (n_492));
  sg13g2_buf_1 drc_buf_sp19504(.A (n_352), .X (n_491));
  sg13g2_xnor2_1 g2(.A (chip_sel), .B (n_491), .Y (n_496));
  sg13g2_nand2b_1 g19507(.A_N (n_309), .B (n_286), .Y (n_497));
  sg13g2_xor2_1 g19508(.A (data_in_right_up[8]), .B (n_37), .X (n_498));
endmodule

